// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlayrpnmfnbjlxgnkczv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsYXlycG5tZm5iamx4Z25rY3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1NDIwMjUsImV4cCI6MjA4NzExODAyNX0.jX86ITEsC0A8dPweGdw9WA-cxJcnDzN79b6dJd9wvcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});